### ISSUE TITLE
Need Help with Colour.

### ISSUE THREAD

**Issue by teilzeitreisender** [lostfocus/wp-advent#1]
I Install your Plugin on my Blog teilzeitreisender.de - it ist also found on reisebloggeradvent.de. Since your last update the picture hat a milky like look. Is it possible to fix it. I have no idea to work with css and java - so hope you can help me an easy way.

**Comment by lostfocus** [comment]
Hi - well, that's a bit how it is supposed to look - the doors get visible/clickable as soon as that day is reached. So on December 1st, the first door will stop being milky and so on.
If you have that page open in the WordPress backend and click on "Preview/Vorschau" you'll see the calendar in its full enabled glory.

**Comment by teilzeitreisender** [comment]
Thank you for your fast response 
Is there any chance to make it "darker"? On the left site on my page it is darker. But its fine if it is changing in Adventszeit. Thank you for this great plugin.

**Comment by lostfocus** [comment]
It should be possible to do that with the theme css. The small left border on your calendar is some small change that comes with your theme, too.
