### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Silvi0102** [lostfocus/wp-advent#2]
Hello,

Unfortunately, my english is not that good, which is why I translate with Google. I like to use this plague. Unfortunately, I have a problem with the new update. Unfortunately, I am not at all proficient in such a thing. I would like to see again that 30 calendars are displayed instead of 24 in the calendar so that I can use it for my anniversary calendar as well. Unfortunately, that does not work anymore. Can someone help me as soon as possible?

Warm greetings from Germany

**Comment by lostfocus** [comment]
Hi Silvi,

bist Du sicher, dass es unser Plugin war, mit dem Du die 30 Tage und an einem speziellen Datum hinbekommst hast? Wir hatten eigentlich von Anfang an immer alles so programmiert, dass es fest die Tage vom 1. bis zum 24. Dezember sind. Das ist auch so ziemlich der Kern des ganzen Plugins - wenn wir das ändern wollten, müssten wir es komplett wieder von Null anfangen. 
Es tut mir für deinen Fall jetzt natürlich ein bisschen Leid, aber wir werden das erstmal nicht machen. Ich hoffe, Du findest irgendwo eine Lösung, die besser für Dich funktioniert!

---

Are you sure you managed to use our plugin to have a 30 day calendar with a special date? We've written the plugin with the 24 days in December at its core, so if we wanted to make this customizable, we had to start all over and write the plugin from scratch.
I'm sorry that we can't help you with your idea but we won't change the plugin that much. I hope you find a solution that works for you!
