### ISSUE TITLE
How can i test the Plugin?

### ISSUE THREAD

**Issue by KevinR23** [lostfocus/wp-advent#3]
i wanted to test your plugin for a customer. he wants to you the "Adventskalender"-function in april. but it seems your plugin only enables the fields in december. is there a easy way to use the calender in another month? i cant even click my pages to test them, because i'm not in december. can you help me out?

bye
kevin

**Comment by lostfocus** [comment]
Hi Kevin,
yeah, December is hard-coded in. If you still want to test it - when you open the page with the shortcode (no block yet, sorry.) in preview mode, the calendar will show up and you can click on the calendar pages.
