### ISSUE TITLE
Don´t find the calendar

### ISSUE THREAD

**Issue by Asarag** [lostfocus/wp-advent#4]
Hello there, I just installed and activated the plugin. I am trying to create a new calendar by giving a name to it, but nothing happens. Could it be that there is a conflict with another calendar on the page? Or did I miss to do something else...
Thanks Astrid

**Comment by lostfocus** [comment]
Hi Astrid,
did you add the calendar shortcode to a page, yet?

**Comment by Asarag** [comment]
Thanks for your question Lostfocus,
I did not find a page where I can look up shortcodes as well...
The link on the Plugin Info comes directly here...
Thanks Astrid

**Comment by lostfocus** [comment]
Hi. Under Tools -> Advent Calendar it should look like this:

<img width="422" alt="Screenshot 2019-11-07 at 11 00 33" src="https://user-images.githubusercontent.com/45055/68379365-00293980-014e-11ea-8e58-d189003ee51f.png">

and after sending this, you get the shortcode like this:

<img width="1728" alt="Screenshot 2019-11-07 at 11 00 44" src="https://user-images.githubusercontent.com/45055/68379408-11724600-014e-11ea-9a57-ee634d6fcf14.png">

This is also where you set the calendar image and where you can add content to the calendar sheets.

**Comment by Asarag** [comment]
I guess that is where it is not working. When I click "Add new calendar" nothing happens... I can see that it is trying to work something out at "Waiting for pixel.wp.com", than the page seems to be reloaded but looks just like before...  The newly named calendar is not created or shows anything...

**Comment by lostfocus** [comment]
Huh, that's peculiar, I've never seen that one before. `pixel.wp.com` sounds like it could be something from the Jetpack plugin or some other Automattic plugin that sends form click data to some tracker.

**Comment by Asarag** [comment]
Mhm, so I am not a programmer or developer, what can I do? Do you have an idea? 

I have jetpack installed and as well (I think you are german, right?):

Buchungskalender - Online reservation and availability checking service for your site. von wpdevelop

Event Organiser - Erstellt einen individuellen  Termin mit Features wie wiederholende Termine, Veranstaltungsorte,  Google-Maps-Karte, Kalenderansichten und -termine und Seiten für  Veranstaltungsorte Von Stephen Harris 

which I thought could be in conflict with another calendar?

Any idea what I can do? Or do you think you can help me with that?
Thank you

**Comment by lostfocus** [comment]
I don't really know any of these plugins and it's a sad fact of the WordPress Ecosystem that it's not always possible to understand how plugins interact with each other. My attempt would be to disable some plugins and see which combination is the problematic one. 🤷‍♂

**Comment by alexschnapper** [comment]
Hi you both - maybe @Asarag is using a blog in the wordpress.com system and not a self-hosted one. Maybe this could be conflicting.

I just tried it on my self-hosted blog and it also works in the preview. Version Wordpress 5.0.3

In german:

1. Im Wordpress-Backend auf "Werkzeuge" und dann auf "Adventskalender" klicken 
2. Einen Namen im Feld "Name des neuen Kalenders:" eingeben und auf den Button "Neuen Kalender hinzufügen"
3. Danach erscheint unterhalb "Alle Kalender" der Shortcode für den eben erzeugten Kalender
4. Bei Anklicken der Zahlen im rechten Bereich können die Inhalte zu den Tagen hinzugefügt/erstellt werden.

![wordpress-calendarview](https://user-images.githubusercontent.com/1958292/69669204-adc6a300-1091-11ea-9199-02302bebf0b4.png)

5. Diesen Shortcode dann in einer anderen Seite oder in einem Beitrag einfügen und dann ist der Adventskalender sichtbar.

War dies hilfreich / Was this helpful?

**Comment by Asarag** [comment]
Thanks you two, but no, unfortunately it is not working. I deactivated the plugins Buchungskalender and Event organizer, jetpack, and others but could not find out which one is conflicting. I am with 1und1 and loaded the wordpress plugin myself on the webspace -  if that was your question?

**Comment by alexschnapper** [comment]
Hi @Asarag did it work out until now or do you still have issues with it? I have also updated my issue https://github.com/lostfocus/wp-advent/issues/5 with Version 5.3 of WordPress. 

Please update the ticket or close the issue ;-)
