### ISSUE TITLE
Your Plugin works with WordPress 5.3 

### ISSUE THREAD

**Issue by alexschnapper** [lostfocus/wp-advent#5]
Hi, don't know if you have tested your plugin with the latest WordPress 5.3 - but as far as I can see it works. Thought you might want to update your info for interested users. And perhaps this issue helps.

![wpadvent_plugin](https://user-images.githubusercontent.com/1958292/69669479-3e04e800-1092-11ea-96da-ea4a990113ec.png)

I also forked your project to perhaps add some languages or test features.

**Comment by lostfocus** [comment]
Hi Alex and thanks! I'll update that as soon as possible, thanks!

**Comment by marcellotogg** [comment]
Hi Alex, based on your post I installed the plugin. But no menue item appears. Have you any idea why. Is there anywhere a documentation of the shortcodes, to include the calendar manually?
Thanks

**Comment by alexschnapper** [comment]
> 
> 
> Hi Alex, based on your post I installed the plugin. But no menue item appears. Have you any idea why. Is there anywhere a documentation of the shortcodes, to include the calendar manually?
> Thanks

Hi Marcello, I also just installed it again and checked it. I could install it on my wordpress version Wordpress 5.5.3.

I know, the documentation is not very helpful for the beginning at the moment..

After activating the plugin check your dashboard and under "tools" you can find the advent plugin. 

/wp-admin/tools.php?page=wp_advent_plugin
